services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenJuergens\DisableBeuser\:
    resource: '../Classes/*'

  SvenJuergens\DisableBeuser\Task\DisableBeuser:
    public: true
