# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2015
  project: Disable BeUser Task
  version: .
  release: 
  latex_documents:
  - - Index
    - disable_beuser.tex
    - Disable BeUser Task
    - 
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
